defmodule Tunez.Repo.Migrations.AddUniqueAlbumNamesPerArtist do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop constraint(:albums, "albums_artist_id_fkey")

    alter table(:albums) do
      modify :artist_id,
             references(:artists,
               column: :id,
               name: "albums_artist_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    create index(:albums, [:artist_id])

    create unique_index(:albums, [:name, :artist_id],
             name: "albums_unique_album_names_per_artist_index"
           )
  end

  def down do
    drop_if_exists unique_index(:albums, [:name, :artist_id],
                     name: "albums_unique_album_names_per_artist_index"
                   )

    drop_if_exists index(:albums, [:artist_id])

    drop constraint(:albums, "albums_artist_id_fkey")

    alter table(:albums) do
      modify :artist_id,
             references(:artists,
               column: :id,
               name: "albums_artist_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end
  end
end
