defmodule Tunez.Repo.Migrations.RemoveNotificationAlbumCascadeDelete do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop constraint(:notifications, "notifications_album_id_fkey")

    alter table(:notifications) do
      modify :album_id,
             references(:albums,
               column: :id,
               name: "notifications_album_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end
  end

  def down do
    drop constraint(:notifications, "notifications_album_id_fkey")

    alter table(:notifications) do
      modify :album_id,
             references(:albums,
               column: :id,
               name: "notifications_album_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end
  end
end
