defmodule Tunez.Repo.Migrations.CreateArtistFollowers do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:artist_followers, primary_key: false) do
      add :artist_id,
          references(:artists,
            column: :id,
            name: "artist_followers_artist_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          primary_key: true,
          null: false

      add :follower_id,
          references(:users,
            column: :id,
            name: "artist_followers_follower_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          primary_key: true,
          null: false
    end

    create index(:artist_followers, [:artist_id])
  end

  def down do
    drop_if_exists index(:artist_followers, [:artist_id])

    drop constraint(:artist_followers, "artist_followers_artist_id_fkey")

    drop constraint(:artist_followers, "artist_followers_follower_id_fkey")

    drop table(:artist_followers)
  end
end
