defmodule Tunez.Repo.Migrations.CreateNotifications do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:notifications, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "notifications_user_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          )

      add :album_id,
          references(:albums,
            column: :id,
            name: "notifications_album_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end

    create index(:notifications, [:user_id])
  end

  def down do
    drop_if_exists index(:notifications, [:user_id])

    drop constraint(:notifications, "notifications_user_id_fkey")

    drop constraint(:notifications, "notifications_album_id_fkey")

    drop table(:notifications)
  end
end
