defmodule TaskManager.Repo.Migrations.CreatedReqisterForOrg do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:organizations) do
      add :owner_id,
          references(:users,
            column: :id,
            name: "organizations_owner_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:organizations, "organizations_owner_id_fkey")

    alter table(:organizations) do
      remove :owner_id
    end
  end
end
