defmodule TaskManager.Repo.Migrations.AddedMemberships do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:memberships, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :role, :text, default: "member"

      add :joined_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :organization_id,
          references(:organizations,
            column: :id,
            name: "memberships_organization_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :user_id,
          references(:users,
            column: :id,
            name: "memberships_user_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create unique_index(:memberships, [:organization_id, :user_id],
             name: "memberships_unique_membership_index"
           )
  end

  def down do
    drop_if_exists unique_index(:memberships, [:organization_id, :user_id],
                     name: "memberships_unique_membership_index"
                   )

    drop constraint(:memberships, "memberships_organization_id_fkey")

    drop constraint(:memberships, "memberships_user_id_fkey")

    drop table(:memberships)
  end
end
