/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface ExampleHoc {
        "first": string;
        "last": string;
        "middle": string;
    }
    interface MyComponent {
        "fullname": string;
    }
}
declare global {
    interface HTMLExampleHocElement extends Components.ExampleHoc, HTMLStencilElement {
    }
    var HTMLExampleHocElement: {
        prototype: HTMLExampleHocElement;
        new (): HTMLExampleHocElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "example-hoc": HTMLExampleHocElement;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface ExampleHoc {
        "first"?: string;
        "last"?: string;
        "middle"?: string;
    }
    interface MyComponent {
        "fullname"?: string;
    }
    interface IntrinsicElements {
        "example-hoc": ExampleHoc;
        "my-component": MyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "example-hoc": LocalJSX.ExampleHoc & JSXBase.HTMLAttributes<HTMLExampleHocElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
