{application,ets,
             [{config_mtime,1736964904},
              {optional_applications,[]},
              {applications,[kernel,stdlib,elixir,logger]},
              {description,"Elixir wrapper for the Erlang :ets module."},
              {modules,['Elixir.ETS','Elixir.ETS.Bag','Elixir.ETS.Base',
                        'Elixir.ETS.KeyValueSet',
                        'Elixir.ETS.KeyValueSet.Macros','Elixir.ETS.Set',
                        'Elixir.ETS.Utils']},
              {registered,[]},
              {vsn,"0.9.0"}]}.
