defmodule Tunez.Seeder do
  @moduledoc """
  Seed data for the Tunez application.

  All text context generated by ChatGPT 4, and all images generated by Midjourney.
  """

  @spec artists :: list(%{name: binary(), biography: binary()})
  def artists do
    [
      %{
        name: "Anderon",
        biography: """
        Formed in the culturally rich region of Brittany, France, in 2010, Anderon is a folk metal band that distinguishes itself by singing in Gaulish, an ancient Celtic language once spoken across much of Western Europe. The name "Anderon" is derived from a Gaulish word meaning "great water" or "flow," reflecting both the band's deep connection to their Celtic roots and the fluid, dynamic nature of their music.

        Anderon's sound is a powerful blend of traditional metal instruments and various Celtic folk instruments such as the Celtic harp, bagpipes, and bodhrán. Their music captures the spirit of ancient Celtic tales and traditions, bringing them to life with a modern metal twist. The band's lyrics, though sung in a language few understand, speak universally of war, peace, honor, and the mystical bond between the land and its people.

        Their performances are known for their high energy and the theatricality of their stage presence, often featuring elaborate costumes and storytelling elements that transport audiences back to the times of the Gaulish tribes.
        """
      },
      %{name: "Aurea Noctis", biography: ""},
      %{
        name: "Ĉielarko",
        biography: """
        Formed in Belgium, Ĉielarko merges the power of folk metal with the poetic grace of Esperanto, the universal language. Their music celebrates cultural unity and folklore, blending heavy riffs with traditional instruments to tell stories of myth and nature. Known for their dynamic performances, Ĉielarko's songs transport listeners across time and space, celebrating the spirit of global harmony through the power of metal music.
        """
      },
      %{
        name: "Crystal Cove",
        biography: """
        Born from the salty air of the Bahamas, Crystal Cove was founded in 2011 by a group of musicians who shared a passion for the high seas and pirate lore. Their music, infused with rollicking rhythms and haunting melodies, tells tales of forgotten treasures, fierce battles, and mystical encounters on the ocean's vast expanse. As they toured across coastal cities, their theatrical performances, complete with pirate attire and stage props, captivated audiences and solidified their reputation as the premiere pirate metal band.
        """
      },
      %{
        name: "Good Time Crew",
        biography: """
        Good Time Crew is a lively and fun-loving band of four ducks from the sunny shores of Costa del Sol, Spain. With a passion for both music and cricket, Derek, Vinny, Rico, and Corey have created a unique blend of upbeat tunes that celebrate their favorite sport. This quacking quartet has quickly become a favorite among children and families, spreading joy with their catchy songs about cricket adventures. They consist of:

        Derek: The dynamic lead singer and avid cricket batsman. Derek's powerful voice and enthusiasm for the game make him the perfect frontman.
        Vinny: The energetic drummer who loves to keep the beat both on the drums and on the cricket field as a wicketkeeper.
        Rico: The cool guitarist whose smooth riffs are as skillful as his cricket strokes. Rico brings a relaxed vibe to the group.
        Corey: The soulful bassist whose deep grooves anchor the band's sound. Corey is also known for his sharp fielding skills, making him an essential part of the team's success.
        """
      },
      %{
        name: "Hourglass",
        biography: """
        Hourglass emerged from the UK's progressive metal scene in 2014, distinguished by their intricate compositions and philosophical lyrics. The band's music is a complex tapestry of time signatures and poetic narratives that explore themes of time, existence, and the cosmos. Known for their elaborate live shows that blend visuals of celestial phenomena with their soundscapes, Hourglass invites their listeners to a transcendental experience, pushing the boundaries of both music and thought.
        """
      },
      %{
        name: "Infiniverse",
        biography: """
        Infiniverse, hailing from London, is a progressive rock band that emerged in the early 2000s, weaving a tapestry of sound that explores the intersections of human emotion and cosmic phenomena. Known for their complex musical compositions and profound lyrical themes, their work delves into the realms of time, space, and beyond, echoing the expansive and intricate patterns of the universe. Each performance and album is a journey, a symphony of abstract expressions and intricate harmonies, inviting listeners to traverse the mysterious landscapes of the mind and the cosmos through a fusion of haunting melodies and philosophical depth.
        """
      },
      %{
        name: "Leviatã",
        biography: """
        Leviatã was formed in São Paulo in 2014, quickly making a name for themselves in Brazil's metal scene with their intense and unrelenting style of death metal. The band's name, Portuguese for "Leviathan," reflects the monstrous and overwhelming force of their music, which explores themes of chaos, power, and the darker aspects of human nature.

        Their sound is characterized by fast-paced, aggressive drumming, deep guttural vocals, and complex guitar riffs. Leviatã's lyrics often delve into mythology, existential dread, and critiques of societal norms, challenging listeners to confront the abyss both within and around them.

        Their stage presence is commanding, featuring elaborate theatrical elements such as stage props and costumes that enhance the mythological and apocalyptic themes of their music. Leviatã has not only captivated audiences across Brazil but has also begun to gain international recognition for their uncompromising sound and thematic depth.
        """
      },
      %{
        name: "L'orchestre obscur",
        biography: """
        L'orchestre obscur, based in Paris, France, is an ensemble unlike any other, blending the haunting beauty of neoclassical music with the deep, unsettling tones of dark ambient. Formed in 2012, the group consists of classically trained musicians who share a passion for exploring the shadowy realms of sound and emotion.

        Their music serves as a soundtrack for the unspoken, the unseen, and the unknown, weaving together elements of classical orchestration, electronic textures, and ambient noise. The result is a profound auditory experience that invites listeners into a world of introspection and melancholy, yet is also filled with the stark beauty of minimalist composition.

        L'orchestre obscur performances are visual and auditory feasts, often accompanied by dim lighting and abstract visual projections, enhancing the mystique and immersive nature of their live shows. Their music is both an escape and a deep dive into the complexities of human emotions and the darker corners of the classical music world.
        """
      },
      %{
        name: "Lithinex",
        biography: """
        In the mystic lands of Sweden, amidst the echoes of ancient lore, Lithinex was born under the northern lights of 2013. Their music, a symphonic metal journey, weaves a tapestry of dark beauty and complex emotions. The band crafts each song as a chapter of an epic saga, filled with powerful orchestral sweeps and lyrical narratives that explore the depths of the human and mythical soul. Lithinex's concerts are akin to a theatrical performance, where music and visual artistry converge to tell stories of olden times and enchanted realms.
        """
      },
      %{
        name: "Nights in the Nullarbor",
        biography: """
        Nights in the Nullarbor originated from the serene and rugged landscapes of Adelaide, South Australia, Formed in 2017, the band consists of five musicians who met at a local music festival, Their name reflects the vast, open landscapes of the Nullarbor Plain, which is known for its stark beauty and the clear, star-filled nights that engulf it. Their music combines mellow indie rock with subtle influences of folk and ambient sounds, capturing the essence of wide-open spaces and introspective journeys.

        Their lyrical themes often revolve around travel, personal growth, and the nuances of human relationships, set against the backdrop of Australia's picturesque scenery. Nights in the Nullarbor quickly gained a local following with their captivating live performances and the genuine warmth they bring to their shows, making listeners feel as though they are part of a close-knit community.
        """
      },
      %{
        name: "Oáza",
        biography: """
        Formed in Prague in 2016, Oáza is a quintet that has quickly risen to prominence within the Czech alternative rock scene. The band's name, Czech for "oasis," reflects their music's nature: a refreshing refuge from the ordinary, blending poetic lyrics with innovative rock sounds. Oáza's music is characterized by its melodic richness, intricate guitar work, and introspective lyrics, which often explore themes of personal growth, existential reflection, and social commentary.

        Their live performances are renowned for their energy and intimacy, creating a compelling connection with audiences. Oáza's approach to music combines modern influences with traditional Czech musical elements, making their sound distinctly familiar yet uniquely innovative.
        """
      },
      %{
        name: "Pilvipeite",
        biography: """
        Formed in the picturesque landscapes of Finland's vast forests and lakes in 2010, Pilvipeite, which translates to "Cloud Cover" in English, captures the essence of Finnish folklore and nature through their music. The band consists of five members who play a variety of traditional Finnish instruments, such as the kantele (a plucked string instrument), jouhikko (a bowed lyre), and harmonikka (accordion), alongside more conventional folk instruments like the guitar and violin.

        Pilvipeite's music is deeply rooted in the rich traditions of Finnish folk, yet they infuse it with a modern sensibility that appeals to contemporary audiences. Their lyrics, sung in Finnish, weave tales of ancient myths, the beauty and brutality of nature, seasonal cycles, and the Finnish rural lifestyle, reflecting a deep connection to their cultural heritage.

        Their performances are known for their authenticity and intimacy, often evoking the serene, melancholic beauty of the Finnish landscape. Pilvipeite has a loyal following both in Finland and internationally among folk music enthusiasts who appreciate their blend of melancholy melodies, lyrical storytelling, and the haunting beauty of traditional Finnish music.
        """
      },
      %{
        name: "Refrain",
        biography: """
        In the heart of Milan, where ancient echoes meet modern melodies, the saga of Refrain began to unfold in the spring of 2013. Composed of minstrels whose spirits were forged in the fiery furnaces of power metal, they weave a tapestry of tales steeped in the mystique of mythical lands and legendary battles. Their music, a cauldron of soaring melodies and thunderous rhythms, conjures visions of heroic deeds and epic sagas.

        With voices that rise in powerful harmony and guitars that slice through the silence like blades of destiny, Refrain transforms each performance into a ritual, a summoning of ancient powers and forgotten realms. Their songs serve as portals to other worlds, where the valiant stand defiant and the faint-hearted find their courage.
        """
      },
      %{
        name: "Resonanz",
        biography: """
        Formed in the vibrant and tumultuous Berlin music scene of the early 1990s, Resonanz quickly carved out a niche for themselves within the Neue Deutsche Härte movement, drawing comparisons to pioneering acts like Rammstein. Known for their heavy guitar riffs, electronic synth textures, and commanding vocals, Resonanz combines the aggressive force of metal with the industrial sounds that echo the gritty reality of post-reunification Germany.

        Their lyrics, delivered in a mix of German and occasionally English, explore themes of societal issues, personal strife, and the human condition, often presented through powerful, metaphorical imagery. Resonanz's stage presence is intense and theatrical, featuring elaborate lighting, pyrotechnics, and a stark, industrial aesthetic that complements their sonic assault.
        """
      },
      %{name: "Rymdvarelse", biography: ""},
      %{
        name: "Solaris",
        biography: """
        Solaris is a progressive metal band known for their complex compositions and intricate live performances. Formed in 2015 in Melbourne, Australia, the band quickly gained a reputation for their ambitious soundscapes and technical prowess. Comprising five members—a lead vocalist with a dynamic range, two guitarists specializing in both rhythmic complexity and blistering solos, a bassist known for groovy yet intricate lines, and a drummer who combines jazz finesse with metal ferocity—Solaris is a powerhouse on stage. Their music often explores themes of futuristic dystopias and philosophical inquiries into human nature, making each album a thought-provoking journey.
        """
      },
      %{
        name: "Static Shift",
        biography: """
        Static Shift, formed in the United States in 2015, is characterized by its robust incorporation of industrial rock elements.  The band integrates electronic soundscapes with traditional rock instrumentation, creating a sonic foundation that is both gritty and resonant. Their thematic focus on dystopian futures and technological dominance is reflected in their sound, which employs synthesized textures and rhythmic complexity. Static Shift's approach to music production showcases a meticulous attention to digital sound design and dynamic range.
        """
      },
      %{
        name: "Syndicate",
        biography: """
        Syndicate, hailing from Germany, is an esteemed heavy metal ban established in 2012. Renowned for their powerful guitar riffs an thunderous percussion, the band's music delves into themes of rebellion and authority. Syndicate's lyrical content, rich with historical and fantastical references, complements their aggressive musical style. With numerous awards and a dedicated global fanbase, Syndicate remains a prominent and influential force in the heavy metal genre.
        """
      },
      %{
        name: "Tangerine",
        biography: """
        From the neon heart of Los Angeles, Tangerine pulses to life, merging synth waves with the rhythm of the city. Formed in the 2010s, this electronica ensemble distills vibrant beats into sonic experiences that resonate deep and wide. Each track is a burst of color, a splash of emotion, painting the air with the essence of connectivity and transformation. On stage, Tangerine transforms electricity into a spectacle, crafting light and sound into something that doesn't just move you — it transports you. Dive into their universe, where every note is a pixel in a larger canvas of digital wonder.
        """
      },
      %{
        name: "The Lost Keys",
        biography: """
        The Lost Keys are a blues rock band hailing from New Orleans, Louisiana, formed in 2014. The band comprises a group of musicians who found each other through a shared love of vintage blues and the vibrant music scene of their city. Their name reflects both a playful nod to the elusive nature of perfect harmony and the literal experience of losing their van keys after their first gig.

        Known for their gritty guitar riffs, soulful harmonica, and deep, gravelly vocals, The Lost Keys capture the essence of classic blues rock while infusing it with modern sensibilities. Their music tells stories of life's trials and tribulations, love lost and found, and the search for redemption. Their performances are known for their electrifying energy and the way they can turn any venue into a jubilant, foot-stomping hall.
        """
      },
      %{
        name: "Valkyrie's Fury",
        biography: """
        Emerging from the ancient mists of Estonia's mystical forests, Valkyrie's Fury is a symphonic power metal band that channels the spirit and valor of the legendary Valkyries. Formed in the historical heart of Tallinn, the band weaves a sonic tapestry rich with soaring melodies and thundering riffs. Each member is said to embody the essence of a Valkyrie warrior, bringing messages from the gods through their music.

        Their debut album, "Echoes of Valhalla," explores tales of battle, bravery, and the ethereal journey of souls guided by Valkyries. The band's live performances are renowned for their theatrical elements, featuring armor, battle cries, and an immersive stage setup that transports the audience to the heart of Norse mythology.

        Valkyrie's Fury has become a beacon for fans seeking a blend of historical myth and metal, establishing them as one of Estonia's most unique and powerful musical exports.
        """
      },
      %{
        name: "Vanadine",
        biography: """
        Vanadine emerged from the icy expanses of Finland in 2013, crafting a sound as dark and cold as their native winter nights. The band's name, inspired by the element vanadium which is known for its hard, malleable, and corrosion-resistant properties, symbolizes their music's intense, unyielding nature.

        Vanadine is renowned for its aggressive guitar riffs, rapid drumming, and chilling vocal style, which combine to create a raw, atmospheric sound. Their lyrics delve into themes of existential despair, nihilism, and the darker aspects of human nature, often drawing from Nordic mythology and the stark beauty of their homeland.

        Their stage performances are marked by an immersive, ritualistic atmosphere, with members donning corpse paint and using elaborate props to enhance the grim aesthetic. Vanadine's music is not just heard; it's experienced, as a haunting journey through shadowy realms.
        """
      },
      %{
        name: "Violet Depths",
        biography: """
        Origins: Nestled in the vibrant landscapes of Vancouver, Violet Depths emerged from the mists of 2014, where echoes of the city's natural beauty inspired their ambient soundscapes.

        Sound: A tapestry of ethereal synthesizers and layered textures, Violet Depths crafts sound that serves as a canvas for emotional exploration. Their music, a delicate balance of harmony and dissonance, mirrors the complex interplay of light and shadow found in the depths of the ocean.

        Themes: Each album is a voyage through chromatic moods, reflecting varied emotional landscapes with a unique color theme. The band's lyrical content, sparse yet poignant, whispers tales of solitude, introspection, and the subtle interplay between nature and human emotion.

        Live Experience: In their live performances, Violet Depths transforms spaces into immersive sensory experiences, blending visuals and sound to envelop the audience in a cocoon of color and melody.
        """
      },
      %{
        name: "Zombie Kittens!!",
        biography: """
        Zombie Kittens!! burst onto the Tokyo music scene in 2018 with their dynamic blend of pop melodies and metal riffs, wrapped in a visually engaging cartoon style that quickly captivated fans both domestically and internationally. The band is known for its playful yet fierce approach to music, combining catchy hooks with hard-hitting guitar solos, all while maintaining a whimsical and theatrical aesthetic.

        Their name and theme are inspired by a fusion of cute and macabre elements, featuring zombie-themed cartoon kittens that have become iconic characters in their music videos and merchandise. Zombie Kittens!! embraces a light-hearted take on the traditional metal themes of rebellion and darkness, offering instead a colorful, energetic escape into a fantasy world where even the undead can be adorable.
        """
      },
      %{
        name: "Черная Луна",
        biography: """
        Formed in the harsh winters of Moscow in 2016, Черная Луна, translating to "Black Moon" in English, delves deep into the realms of death metal with a distinctly Slavic twist. The band's sound is characterized by its brutal guitar riffs, deep growling vocals, and blistering drum beats, all set against the backdrop of Russia's rich cultural and historical tapestry.

        Черная Луна's lyrics, sung entirely in Russian, explore themes of existential dread, folklore, and the metaphysical struggles between light and darkness. Their music is a reflection of the stark, often unforgiving nature of the Russian landscape, intertwined with the mystic allure of Slavic mythology.

        The band has quickly risen in the ranks of the Russian metal scene, known for their intense live performances that captivate audiences with both their musical prowess and their thematic depth. Their shows often feature theatrical elements such as elaborate stage setups and costumes that enhance the dark and mystical atmosphere of their performances.
        """
      }
    ]
  end

  @spec albums ::
          list(%{
            name: binary(),
            artist_name: binary(),
            year_released: integer(),
            cover_image_url: binary(),
            tracks: list(%{name: binary(), duration: binary(), duration_seconds: integer()})
          })
  def albums do
    [
      %{
        name: "A Crack in the Road",
        cover_image_url: "/images/albums/nights_in_the_nullarbor_a_crack_in_the_road.png",
        year_released: 2021,
        artist_name: "Nights in the Nullarbor",
        tracks: [
          %{name: "Road Less Travelled", duration: "4:25", duration_seconds: 265},
          %{name: "Dusk Till Dawn", duration: "3:55", duration_seconds: 235},
          %{name: "Mirage", duration: "4:40", duration_seconds: 280},
          %{name: "Lost Highways", duration: "5:05", duration_seconds: 305},
          %{name: "Passing Lights", duration: "3:30", duration_seconds: 210},
          %{name: "Freewheeler", duration: "4:59", duration_seconds: 299},
          %{name: "Sand and Sun", duration: "4:16", duration_seconds: 256},
          %{name: "Outback Serenade", duration: "5:22", duration_seconds: 322},
          %{name: "Restless Wind", duration: "4:38", duration_seconds: 278},
          %{name: "Homeward Bound", duration: "4:47", duration_seconds: 287}
        ]
      },
      %{
        name: "Abyssal Gates",
        year_released: 2017,
        artist_name: "Leviatã",
        tracks: [
          %{name: "Depths Unseen", duration: "4:15", duration_seconds: 255},
          %{name: "Serpent's Embrace", duration: "3:50", duration_seconds: 230},
          %{name: "Echoes of the Void", duration: "5:40", duration_seconds: 340},
          %{name: "Into the Abyss", duration: "4:25", duration_seconds: 265},
          %{name: "Dark Waters", duration: "6:00", duration_seconds: 360},
          %{name: "Gateways to Oblivion", duration: "4:45", duration_seconds: 285},
          %{name: "Shadow Dominion", duration: "5:15", duration_seconds: 315},
          %{name: "What Lies Beneath", duration: "4:30", duration_seconds: 270}
        ]
      },
      %{
        name: "Amber Reverie",
        cover_image_url: "/images/albums/violet_depths_amber_reverie.png",
        year_released: 2017,
        artist_name: "Violet Depths",
        tracks: [
          %{name: "Glow of the Horizon", duration: "5:15", duration_seconds: 315},
          %{name: "Sands of Time", duration: "4:40", duration_seconds: 280},
          %{name: "Echoes of Warmth", duration: "6:00", duration_seconds: 360},
          %{name: "Dusk's Embrace", duration: "5:50", duration_seconds: 350},
          %{name: "Golden Hues", duration: "3:45", duration_seconds: 225},
          %{name: "Whispering Dunes", duration: "4:30", duration_seconds: 270},
          %{name: "Shifting Shadows", duration: "5:10", duration_seconds: 310},
          %{name: "Veil of Light", duration: "6:25", duration_seconds: 385},
          %{name: "Serenity Calls", duration: "4:55", duration_seconds: 295},
          %{name: "Last Rays", duration: "6:10", duration_seconds: 370},
          %{name: "Desert Whisper", duration: "5:00", duration_seconds: 300},
          %{name: "Afterglow", duration: "4:35", duration_seconds: 275}
        ]
      },
      %{
        name: "Astral Legacy",
        cover_image_url: "/images/albums/solaris_astral_legacy.png",
        year_released: 2019,
        artist_name: "Solaris",
        tracks: [
          %{name: "Stellar Prelude", duration: "2:30", duration_seconds: 150},
          %{name: "Forged in Time", duration: "4:00", duration_seconds: 240},
          %{name: "City Lights", duration: "4:10", duration_seconds: 250},
          %{name: "Journeyman", duration: "6:05", duration_seconds: 365},
          %{name: "Starlit Rememberance", duration: "4:13", duration_seconds: 253},
          %{name: "Echoes of Infinity", duration: "3:45", duration_seconds: 225},
          %{name: "Valkyrie's Vigil", duration: "4:05", duration_seconds: 245},
          %{name: "Lunar Solitude", duration: "8:45", duration_seconds: 525},
          %{name: "Revival Sparks", duration: "5:13", duration_seconds: 313},
          %{name: "Chronicles", duration: "6:15", duration_seconds: 375}
        ]
      },
      %{
        name: "Azure Pulse",
        cover_image_url: "/images/albums/tangerine_azure_pulse.png",
        year_released: 2019,
        artist_name: "Tangerine",
        tracks: [
          %{name: "Midnight Wave", duration: "4:15", duration_seconds: 255},
          %{name: "Echoes of the Deep", duration: "5:30", duration_seconds: 330},
          %{name: "Neon Current", duration: "4:40", duration_seconds: 280},
          %{name: "Twilight Synth", duration: "3:55", duration_seconds: 235},
          %{name: "Oceanic", duration: "5:25", duration_seconds: 325},
          %{name: "Blue Horizon", duration: "4:01", duration_seconds: 241},
          %{name: "Starlight Tide", duration: "5:22", duration_seconds: 322},
          %{name: "Depths of Blue", duration: "6:00", duration_seconds: 360},
          %{name: "Celestial Voyage", duration: "3:12", duration_seconds: 192},
          %{name: "Luminescent Sea", duration: "5:13", duration_seconds: 313}
        ]
      },
      %{
        name: "Backdoor Blues",
        cover_image_url: "/images/albums/the_lost_keys_backdoor_blues.png",
        year_released: 2018,
        artist_name: "The Lost Keys",
        tracks: [
          %{name: "Midnight Drifter", duration: "4:50", duration_seconds: 290},
          %{name: "Whiskey and Tears", duration: "3:30", duration_seconds: 210},
          %{name: "Crossroads Deal", duration: "5:15", duration_seconds: 315},
          %{name: "Heartbreak Hotel", duration: "4:40", duration_seconds: 280},
          %{name: "Smoky Haze", duration: "3:55", duration_seconds: 235},
          %{name: "Velvet Night", duration: "4:25", duration_seconds: 265},
          %{name: "Rusted Strings", duration: "5:00", duration_seconds: 300},
          %{name: "Echoes of the Past", duration: "3:45", duration_seconds: 225},
          %{name: "Soul Serenade", duration: "4:10", duration_seconds: 250},
          %{name: "Last Call Blues", duration: "5:20", duration_seconds: 320}
        ]
      },
      %{
        name: "Beyond the Event Horizon",
        cover_image_url: "/images/albums/solaris_beyond_the_event_horizon.png",
        year_released: 2023,
        artist_name: "Solaris",
        tracks: [
          %{name: "Singularity", duration: "3:18", duration_seconds: 198},
          %{name: "Through the Wormhole", duration: "4:22", duration_seconds: 262},
          %{name: "Echoes of Time", duration: "6:01", duration_seconds: 361},
          %{name: "Stardust Memory", duration: "5:03", duration_seconds: 303},
          %{name: "Gravitational Pull", duration: "4:11", duration_seconds: 251},
          %{name: "Quantum Leap", duration: "4:19", duration_seconds: 259},
          %{name: "The Nebula Suite", duration: "6:11", duration_seconds: 371},
          %{name: "Collapsing Stars", duration: "3:46", duration_seconds: 226},
          %{name: "Return to the Void", duration: "7:26", duration_seconds: 446}
        ]
      },
      %{
        name: "Cathedral of Nightmares",
        cover_image_url: "/images/albums/vanadine_cathedral_of_nightmares.png",
        year_released: 2020,
        artist_name: "Vanadine",
        tracks: [
          %{name: "Descent into Madness", duration: "4:30", duration_seconds: 270},
          %{name: "Chants of the Damned", duration: "5:20", duration_seconds: 320},
          %{name: "Altar of Shadows", duration: "5:50", duration_seconds: 350},
          %{name: "Wraiths in the Belfry", duration: "5:15", duration_seconds: 315},
          %{name: "Cloak of Fear", duration: "4:40", duration_seconds: 280},
          %{name: "The Unseen Hand", duration: "5:55", duration_seconds: 355},
          %{name: "Bell Tolls for the Lost", duration: "6:35", duration_seconds: 395},
          %{name: "Cathedral of Nightmares", duration: "7:45", duration_seconds: 465}
        ]
      },
      %{
        name: "Cerulean Fantasy",
        cover_image_url: "/images/albums/violet_depths_cerulean_fantasy.png",
        year_released: 2016,
        artist_name: "Violet Depths",
        tracks: [
          %{name: "Whispers of the Tide", duration: "4:10", duration_seconds: 250},
          %{name: "Beneath the Surface", duration: "5:05", duration_seconds: 305},
          %{name: "Sailing the Solar Winds", duration: "4:50", duration_seconds: 290},
          %{name: "Depths Uncharted", duration: "6:40", duration_seconds: 400},
          %{name: "Reflections in Blue", duration: "3:30", duration_seconds: 210},
          %{name: "Luminous Drift", duration: "5:20", duration_seconds: 320},
          %{name: "A Murmur in the Void", duration: "4:55", duration_seconds: 295},
          %{name: "The Infinite Blue", duration: "7:15", duration_seconds: 435}
        ]
      },
      %{
        name: "Chalice of Valor",
        cover_image_url: "/images/albums/valkyries_fury_chalice_of_valor.png",
        year_released: 2021,
        artist_name: "Valkyrie's Fury",
        tracks: [
          %{name: "Awakening", duration: "4:12", duration_seconds: 252},
          %{name: "Unbreakable", duration: "3:48", duration_seconds: 228},
          %{name: "Chalice of Valor", duration: "5:15", duration_seconds: 315},
          %{name: "Journey into the Unknown", duration: "4:30", duration_seconds: 270},
          %{name: "Forged in the Fires of Destiny", duration: "4:02", duration_seconds: 242},
          %{name: "Beyond the Horizon", duration: "5:06", duration_seconds: 306},
          %{name: "Fading Memories", duration: "3:40", duration_seconds: 220},
          %{name: "Guiding Light", duration: "5:25", duration_seconds: 325},
          %{name: "Reflections", duration: "3:35", duration_seconds: 215},
          %{name: "Battle Lines", duration: "4:55", duration_seconds: 295},
          %{name: "Under Starry Skies", duration: "3:58", duration_seconds: 238},
          %{name: "Eternal Bonds", duration: "7:10", duration_seconds: 430}
        ]
      },
      %{
        name: "Chronicles of the Crown",
        cover_image_url: "/images/albums/refrain_chronicles_of_the_crown.png",
        year_released: 2017,
        artist_name: "Refrain",
        tracks: [
          %{name: "Throne of Twilight", duration: "4:15", duration_seconds: 255},
          %{name: "The Paladin's Oath", duration: "5:05", duration_seconds: 305},
          %{name: "Mists of Avalon", duration: "4:52", duration_seconds: 292},
          %{name: "Shadows Over Camelot", duration: "6:43", duration_seconds: 403},
          %{name: "Minstrels of the Moonlight", duration: "5:31", duration_seconds: 331},
          %{name: "Siege of the Enchanted Castle", duration: "3:43", duration_seconds: 223},
          %{name: "March of the Elders", duration: "5:00", duration_seconds: 300},
          %{name: "Lament for a Fallen King", duration: "6:01", duration_seconds: 361},
          %{name: "Shieldmaidens' Vigil", duration: "3:31", duration_seconds: 211},
          %{name: "Prophecy Fulfilled", duration: "7:02", duration_seconds: 422}
        ]
      },
      %{
        name: "Chronicles of the Lost",
        cover_image_url: "/images/albums/hourglass_chronicles_of_the_lost.png",
        year_released: 2022,
        artist_name: "Hourglass",
        tracks: [
          %{name: "Whispering Tomes", duration: "5:05", duration_seconds: 305},
          %{name: "Shadows of Lore", duration: "4:40", duration_seconds: 280},
          %{name: "Veil of Ages", duration: "5:35", duration_seconds: 335},
          %{name: "Forgotten Realms", duration: "5:15", duration_seconds: 315},
          %{name: "Echoes Through Time", duration: "5:00", duration_seconds: 300},
          %{name: "The Alchemist's Tale", duration: "3:32", duration_seconds: 212},
          %{name: "Scribe's Vision", duration: "6:13", duration_seconds: 373},
          %{name: "Lost Empires", duration: "4:32", duration_seconds: 272},
          %{name: "Myth Weaver", duration: "5:16", duration_seconds: 316},
          %{name: "Timebound", duration: "7:06", duration_seconds: 426}
        ]
      },
      %{
        name: "Cosmic Symphony",
        cover_image_url: "/images/albums/infiniverse_cosmic_symphony.png",
        year_released: 2003,
        artist_name: "Infiniverse",
        tracks: [
          %{name: "Stardust Melody", duration: "4:40", duration_seconds: 280},
          %{name: "Galactic Rhapsody", duration: "5:30", duration_seconds: 330},
          %{name: "Nebula Dance", duration: "4:50", duration_seconds: 290},
          %{name: "Interstellar Ode", duration: "6:35", duration_seconds: 395},
          %{name: "Quantum Leap", duration: "5:20", duration_seconds: 320},
          %{name: "Void Serenade", duration: "4:20", duration_seconds: 260},
          %{name: "Orion's Belt", duration: "5:15", duration_seconds: 315},
          %{name: "Solar Winds", duration: "6:00", duration_seconds: 360},
          %{name: "Through the Cosmos", duration: "5:50", duration_seconds: 350},
          %{name: "Starborn", duration: "6:25", duration_seconds: 385}
        ]
      },
      %{
        name: "Crimson Echoes",
        cover_image_url: "/images/albums/violet_depths_crimson_echoes.png",
        year_released: 2023,
        artist_name: "Violet Depths",
        tracks: [
          %{name: "Last Light", duration: "4:50", duration_seconds: 290},
          %{name: "Through the Scarlet Veil", duration: "5:35", duration_seconds: 335},
          %{name: "Shadows of Red", duration: "6:05", duration_seconds: 365},
          %{name: "Painted Skies", duration: "4:40", duration_seconds: 280},
          %{name: "Echoes of the Heart", duration: "5:25", duration_seconds: 325},
          %{name: "Blood Moon", duration: "4:30", duration_seconds: 270},
          %{name: "Velvet Dusk", duration: "5:15", duration_seconds: 315},
          %{name: "Whispers of the Old City", duration: "7:20", duration_seconds: 440},
          %{name: "Fading Embers", duration: "5:10", duration_seconds: 310},
          %{name: "Red Horizon", duration: "4:45", duration_seconds: 285},
          %{name: "Gilded Silence", duration: "6:20", duration_seconds: 380},
          %{name: "Nightfall Serenade", duration: "5:30", duration_seconds: 330},
          %{name: "Crimson Farewell", duration: "7:45", duration_seconds: 465}
        ]
      },
      %{
        name: "Crown of Shadows",
        cover_image_url: "/images/albums/lithinex_crown_of_shadows.png",
        year_released: 2015,
        artist_name: "Lithinex",
        tracks: [
          %{name: "Whispering Night", duration: "4:10", duration_seconds: 250},
          %{name: "The Throne of Ice", duration: "5:55", duration_seconds: 355},
          %{name: "Shadows Dance", duration: "4:40", duration_seconds: 280},
          %{name: "Frostbitten Kingdom", duration: "7:02", duration_seconds: 422},
          %{name: "Winter's Lament", duration: "6:18", duration_seconds: 378},
          %{name: "Queen of the Dark", duration: "5:45", duration_seconds: 345},
          %{name: "Enthroned in Ice", duration: "4:33", duration_seconds: 273},
          %{name: "Midnight Solstice", duration: "3:57", duration_seconds: 237},
          %{name: "Palace of the Cursed", duration: "5:04", duration_seconds: 304},
          %{name: "Echoes of the Fallen", duration: "6:01", duration_seconds: 361}
        ]
      },
      %{
        name: "Druidh Dubh",
        cover_image_url: "/images/albums/anderon_druidh_dubh.png",
        year_released: 2017,
        artist_name: "Anderon",
        tracks: [
          %{name: "Maros", duration: "4:10", duration_seconds: 250},
          %{name: "Bitu-rigos", duration: "5:30", duration_seconds: 330},
          %{name: "Uindos", duration: "3:45", duration_seconds: 225},
          %{name: "Nertos", duration: "4:12", duration_seconds: 252},
          %{name: "Giamonios", duration: "4:53", duration_seconds: 293},
          %{name: "Dumnos", duration: "6:00", duration_seconds: 360},
          %{name: "Nemeton", duration: "3:44", duration_seconds: 224},
          %{name: "Gaisos", duration: "4:43", duration_seconds: 283},
          %{name: "Lugus", duration: "7:51", duration_seconds: 471}
        ]
      },
      %{
        name: "Quack of the Bat",
        cover_image_url: "/images/albums/good_time_crew_quack_of_the_bat.png",
        year_released: 2023,
        artist_name: "Good Time Crew",
        tracks: [
          %{name: "Golden Derek", duration: "3:15", duration_seconds: 195},
          %{name: "Sunny Cricket Field", duration: "2:50", duration_seconds: 170},
          %{name: "MAXIMO", duration: "3:30", duration_seconds: 210},
          %{name: "Don't Fear the Killer Pythons", duration: "3:45", duration_seconds: 225},
          %{name: "Pitch Perfect", duration: "3:35", duration_seconds: 215},
          %{name: "Good Time Quackers", duration: "4:05", duration_seconds: 245},
          %{name: "A Bowl of Rasmalai", duration: "4:12", duration_seconds: 252},
          %{name: "Match Day Magic", duration: "3:20", duration_seconds: 200},
          %{name: "Seis Carreras Más", duration: "6:01", duration_seconds: 361},
          %{name: "Duck's Victory Dance", duration: "4:00", duration_seconds: 240}
        ]
      },
      %{
        name: "Echo der Stille",
        cover_image_url: "/images/albums/resonanz_echo_der_stille.png",
        year_released: 1999,
        artist_name: "Resonanz",
        tracks: [
          %{name: "Verlorene Seelen", duration: "5:05", duration_seconds: 305},
          %{name: "Stille Schreie", duration: "4:40", duration_seconds: 280},
          %{name: "Kaltes Glas", duration: "4:25", duration_seconds: 265},
          %{name: "Echo der Stille", duration: "5:50", duration_seconds: 350},
          %{name: "Zerrissene Bande", duration: "4:35", duration_seconds: 275},
          %{name: "Gegen den Strom", duration: "5:10", duration_seconds: 310},
          %{name: "Gefrorener Schrei", duration: "6:50", duration_seconds: 410},
          %{name: "Leere Welten", duration: "4:40", duration_seconds: 280},
          %{name: "Klang der Stille", duration: "7:15", duration_seconds: 435},
          %{name: "Nachtflüstern", duration: "5:20", duration_seconds: 320}
        ]
      },
      %{
        name: "Echoes of Valhalla",
        cover_image_url: "/images/albums/valkyries_fury_echoes_of_valhalla.png",
        year_released: 2019,
        artist_name: "Valkyrie's Fury",
        tracks: [
          %{name: "Warrior's Dawn", duration: "4:32", duration_seconds: 272},
          %{name: "Shieldmaiden's Call", duration: "5:16", duration_seconds: 316},
          %{name: "Mists of Niflheim", duration: "3:58", duration_seconds: 238},
          %{name: "Swords against Fate", duration: "4:47", duration_seconds: 287},
          %{name: "Feast for the Fallen", duration: "5:20", duration_seconds: 320},
          %{name: "Ride of the Valkyries", duration: "6:49", duration_seconds: 409},
          %{name: "Whispers of the Seer", duration: "4:15", duration_seconds: 255},
          %{name: "The Last Stand", duration: "7:02", duration_seconds: 422},
          %{name: "Journey to the Afterlife", duration: "5:36", duration_seconds: 336},
          %{name: "Saga of the Endless", duration: "10:45", duration_seconds: 645}
        ]
      },
      %{
        name: "Echoes Through Eternity",
        cover_image_url: "/images/albums/infiniverse_echoes_through_eternity.png",
        year_released: 2001,
        artist_name: "Infiniverse",
        tracks: [
          %{name: "Time Spiral", duration: "5:10", duration_seconds: 310},
          %{name: "Echoes", duration: "4:55", duration_seconds: 295},
          %{name: "Infinity's Edge", duration: "6:00", duration_seconds: 360},
          %{name: "Celestial Voyage", duration: "5:25", duration_seconds: 325},
          %{name: "Event Horizon", duration: "7:15", duration_seconds: 435},
          %{name: "Vortex of Time", duration: "5:40", duration_seconds: 340},
          %{name: "The Ancient Pulse", duration: "4:50", duration_seconds: 290},
          %{name: "Lapsi", duration: "3:55", duration_seconds: 235},
          %{name: "Through the Aeon", duration: "6:15", duration_seconds: 375},
          %{name: "Temporal Drift", duration: "4:30", duration_seconds: 270}
        ]
      },
      %{
        name: "Eĥoj",
        cover_image_url: "/images/albums/cielarko_ehoj.png",
        year_released: 2016,
        artist_name: "Ĉielarko",
        tracks: [
          %{name: "Ombroj de la Pasinto", duration: "5:13", duration_seconds: 313},
          %{name: "Murmuro de la Ŝtonoj", duration: "4:28", duration_seconds: 268},
          %{name: "Ventegoj de Tempo", duration: "6:02", duration_seconds: 362},
          %{name: "Vagantoj sen Hejmo", duration: "5:12", duration_seconds: 312},
          %{name: "Sekretaj Vojoj", duration: "3:44", duration_seconds: 224},
          %{name: "Vekiĝo de la Terpomoj", duration: "3:18", duration_seconds: 198},
          %{name: "Ĉirkaŭpreno de Historio", duration: "5:04", duration_seconds: 304},
          %{name: "Legendoj Flustritaj", duration: "4:55", duration_seconds: 295}
        ]
      },
      %{
        name: "Emerald Depths",
        cover_image_url: "/images/albums/violet_depths_emerald_depths.png",
        year_released: 2019,
        artist_name: "Violet Depths",
        tracks: [
          %{name: "Heart of the Forest", duration: "4:05", duration_seconds: 245},
          %{name: "Veins of Leaf and Light", duration: "5:30", duration_seconds: 330},
          %{name: "Canopy Whispers", duration: "6:55", duration_seconds: 415},
          %{name: "Moss and Stone", duration: "4:25", duration_seconds: 265},
          %{name: "Green Mist", duration: "5:40", duration_seconds: 340},
          %{name: "Raindrop Serenade", duration: "4:50", duration_seconds: 290},
          %{name: "Roots Entwined", duration: "5:15", duration_seconds: 315},
          %{name: "Eternal Spring", duration: "7:00", duration_seconds: 420},
          %{name: "Undergrowth Echoes", duration: "4:40", duration_seconds: 280},
          %{name: "Dewdrop Dance", duration: "5:05", duration_seconds: 305},
          %{name: "Shade and Light", duration: "4:55", duration_seconds: 295},
          %{name: "Forest's Pulse", duration: "6:30", duration_seconds: 390}
        ]
      },
      %{
        name: "Eternal Tides",
        cover_image_url: "/images/albums/crystal_cove_eternal_tides.png",
        year_released: 2024,
        artist_name: "Crystal Cove",
        tracks: [
          %{name: "Waves of Destiny", duration: "4:45", duration_seconds: 285},
          %{name: "Moonlit Mariners", duration: "5:22", duration_seconds: 322},
          %{name: "Serenade of the Seas", duration: "3:51", duration_seconds: 231},
          %{name: "Eternal Tides", duration: "6:18", duration_seconds: 378},
          %{name: "Ocean's Embrace", duration: "4:30", duration_seconds: 270},
          %{name: "Abyssal Echoes", duration: "5:10", duration_seconds: 310},
          %{name: "Sails of Fate", duration: "4:58", duration_seconds: 298},
          %{name: "Whispers of the Deep", duration: "4:40", duration_seconds: 280},
          %{name: "The Forgotten Isle", duration: "5:35", duration_seconds: 335},
          %{name: "Voyage Eternal", duration: "7:01", duration_seconds: 421}
        ]
      },
      %{
        name: "Flamoj de la Pasinteco",
        cover_image_url: "/images/albums/cielarko_flamoj_de_la_pasinteco.png",
        year_released: 2018,
        artist_name: "Ĉielarko",
        tracks: [
          %{name: "Antikvaj Rakontoj", duration: "4:50", duration_seconds: 290},
          %{name: "Voko de la Antaŭuloj", duration: "5:25", duration_seconds: 325},
          %{name: "Eĥoj de Batalo", duration: "4:39", duration_seconds: 279},
          %{name: "La Kanto de la Ŝtormo", duration: "4:21", duration_seconds: 261},
          %{name: "Koroj Ligita", duration: "3:34", duration_seconds: 214},
          %{name: "Transe de la Fajro", duration: "4:32", duration_seconds: 272},
          %{name: "Sombra Marŝo", duration: "3:10", duration_seconds: 190},
          %{name: "Reveno al la Radikoj", duration: "6:45", duration_seconds: 405}
        ]
      },
      %{
        name: "Furry Fury",
        cover_image_url: "/images/albums/zombie_kittens_furry_fury.png",
        year_released: 2019,
        artist_name: "Zombie Kittens!!",
        tracks: [
          %{name: "Whiskers of Steel", duration: "3:50", duration_seconds: 230},
          %{name: "Paws of Power", duration: "4:15", duration_seconds: 255},
          %{name: "Scratching Post Apocalypse", duration: "4:00", duration_seconds: 240},
          %{name: "Meowtallica", duration: "3:45", duration_seconds: 225},
          %{name: "The Purranormal", duration: "4:20", duration_seconds: 260},
          %{name: "Tail Whip", duration: "3:30", duration_seconds: 210},
          %{name: "Night of the Living Fur", duration: "5:00", duration_seconds: 300},
          %{name: "Clawed Shadows", duration: "4:10", duration_seconds: 250}
        ]
      },
      %{
        name: "Gates of Eternity",
        cover_image_url: "/images/albums/refrain_gates_of_eternity.png",
        year_released: 2020,
        artist_name: "Refrain",
        tracks: [
          %{name: "Dragon's Awakening", duration: "4:45", duration_seconds: 285},
          %{name: "Echoes of the Celestial", duration: "5:30", duration_seconds: 330},
          %{name: "Guardians of the Gate", duration: "4:55", duration_seconds: 295},
          %{name: "The Sorcerer's Pact", duration: "5:40", duration_seconds: 340},
          %{name: "Riddles of the Sphinx", duration: "6:25", duration_seconds: 385},
          %{name: "Serpents in the Mist", duration: "4:02", duration_seconds: 242},
          %{name: "Citadel of Secrets ", duration: "4:10", duration_seconds: 250},
          %{name: "Whispers from the Abyss", duration: "3:45", duration_seconds: 225},
          %{name: "The Oracle's Vision ", duration: "4:50", duration_seconds: 290},
          %{name: "Journey Through the Gates", duration: "6:50", duration_seconds: 410}
        ]
      },
      %{
        name: "Grenzenlos",
        cover_image_url: "/images/albums/resonanz_grenzenlos.png",
        year_released: 2002,
        artist_name: "Resonanz",
        tracks: [
          %{name: "Grenzenlos", duration: "5:14", duration_seconds: 314},
          %{name: "Feuer und Eis", duration: "4:55", duration_seconds: 295},
          %{name: "Neue Welt", duration: "4:45", duration_seconds: 285},
          %{name: "Scherbenmeer", duration: "5:30", duration_seconds: 330},
          %{name: "Schwarzer Regen", duration: "4:50", duration_seconds: 290},
          %{name: "Herz aus Stahl", duration: "5:20", duration_seconds: 320},
          %{name: "Zerbrochene Grenzen", duration: "6:35", duration_seconds: 395},
          %{name: "Wüstengeist", duration: "4:54", duration_seconds: 294},
          %{name: "Flüstern der Nacht", duration: "7:00", duration_seconds: 420},
          %{name: "Unendliche Weiten", duration: "5:35", duration_seconds: 335}
        ]
      },
      %{
        name: "Hranice Neznáma",
        year_released: 2022,
        artist_name: "Oáza",
        tracks: [
          %{name: "Kde končí svět", duration: "4:00", duration_seconds: 240},
          %{name: "Bludiště", duration: "3:55", duration_seconds: 235},
          %{name: "Hvězdy nad námi", duration: "4:40", duration_seconds: 280},
          %{name: "Prostřední země", duration: "5:10", duration_seconds: 310},
          %{name: "Za horizontem", duration: "4:20", duration_seconds: 260},
          %{name: "Záblesk v dálce", duration: "3:31", duration_seconds: 211},
          %{name: "Mezi liniemi", duration: "4:14", duration_seconds: 254},
          %{name: "Cesty domů", duration: "5:00", duration_seconds: 300},
          %{name: "Nový den", duration: "4:25", duration_seconds: 265}
        ]
      },
      %{
        name: "Juuret",
        cover_image_url: "/images/albums/pilvipeite_juuret.png",
        year_released: 2017,
        artist_name: "Pilvipeite",
        tracks: [
          %{name: "Kotipolku", duration: "4:40", duration_seconds: 280},
          %{name: "Sydämeni Laulu", duration: "5:25", duration_seconds: 325},
          %{name: "Metsän Kutsu", duration: "4:55", duration_seconds: 295},
          %{name: "Tuulen Kuiskaus", duration: "5:02", duration_seconds: 302},
          %{name: "Juuret", duration: "6:30", duration_seconds: 390},
          %{name: "Rantakoivun Alla", duration: "3:45", duration_seconds: 225},
          %{name: "Kevään Ensikukat", duration: "4:10", duration_seconds: 250},
          %{name: "Syksyn Sävel", duration: "5:00", duration_seconds: 300},
          %{name: "Talven Taika", duration: "7:55", duration_seconds: 475},
          %{name: "Maamme Laulu", duration: "8:20", duration_seconds: 500}
        ]
      },
      %{
        name: "Masters of the Underground",
        cover_image_url: "/images/albums/syndicate_masters_of_the_underground.png",
        year_released: 2021,
        artist_name: "Syndicate",
        tracks: [
          %{name: "Iron Rule", duration: "4:15", duration_seconds: 255},
          %{name: "Dark Alliances", duration: "5:03", duration_seconds: 303},
          %{name: "Rebel Yell", duration: "4:47", duration_seconds: 287},
          %{name: "Shadow Kingdom", duration: "5:55", duration_seconds: 355},
          %{name: "The Overlord", duration: "6:22", duration_seconds: 382},
          %{name: "Throne of Thorns", duration: "4:40", duration_seconds: 280},
          %{name: "Midnight Raid", duration: "5:15", duration_seconds: 315},
          %{name: "Underworld Rise", duration: "5:00", duration_seconds: 300},
          %{name: "Battle Cry", duration: "4:57", duration_seconds: 297},
          %{name: "Forge the Empire", duration: "6:30", duration_seconds: 390}
        ]
      },
      %{
        name: "Metsänpeitto",
        cover_image_url: "/images/albums/pilvipeite_metsanpeitto.png",
        year_released: 2012,
        artist_name: "Pilvipeite",
        tracks: [
          %{name: "Kuiskaus Koivikossa", duration: "4:15", duration_seconds: 255},
          %{name: "Revontulet", duration: "5:30", duration_seconds: 330},
          %{name: "Pohjolan Talvi", duration: "4:40", duration_seconds: 280},
          %{name: "Sammalkorven Sävel", duration: "3:55", duration_seconds: 235},
          %{name: "Laulujoutsen", duration: "4:25", duration_seconds: 265},
          %{name: "Taiga Tarina", duration: "6:10", duration_seconds: 370},
          %{name: "Pakkasen Puraisu", duration: "5:50", duration_seconds: 350},
          %{name: "Hämärän Hyssy", duration: "7:30", duration_seconds: 450},
          %{name: "Korpikuiskaus", duration: "5:00", duration_seconds: 300},
          %{name: "Metsänpeitto", duration: "8:35", duration_seconds: 515}
        ]
      },
      %{
        name: "Monolith of Wrath",
        year_released: 2020,
        artist_name: "Leviatã",
        tracks: [
          %{name: "Wrath Incarnate", duration: "3:55", duration_seconds: 235},
          %{name: "Titans of Despair", duration: "4:35", duration_seconds: 275},
          %{name: "Herald of Carnage", duration: "5:05", duration_seconds: 305},
          %{name: "Monarch of Shadows", duration: "6:10", duration_seconds: 370},
          %{name: "The Colossus Falls", duration: "4:44", duration_seconds: 284},
          %{name: "Ruins of Power", duration: "5:32", duration_seconds: 332},
          %{name: "Throne of Disgrace", duration: "4:32", duration_seconds: 272},
          %{name: "End of Reign", duration: "5:45", duration_seconds: 345}
        ]
      },
      %{
        name: "Obsidian Pulse",
        cover_image_url: "/images/albums/violet_depths_obsidian_pulse.png",
        year_released: 2021,
        artist_name: "Violet Depths",
        tracks: [
          %{name: "Night's Edge", duration: "4:45", duration_seconds: 285},
          %{name: "Silence in the Shadows", duration: "5:20", duration_seconds: 320},
          %{name: "Reflections of the Void", duration: "6:10", duration_seconds: 370},
          %{name: "Glass Heart", duration: "4:35", duration_seconds: 275},
          %{name: "Stars in the Abyss", duration: "5:50", duration_seconds: 350},
          %{name: "Darkened Mirrors", duration: "4:55", duration_seconds: 295},
          %{name: "Pulse of the Unknown", duration: "5:40", duration_seconds: 340},
          %{name: "Shards of Night", duration: "6:30", duration_seconds: 390},
          %{name: "Crescent Shadows", duration: "5:15", duration_seconds: 315},
          %{name: "Silent Glimmers", duration: "4:20", duration_seconds: 260},
          %{name: "Depth of Darkness", duration: "6:05", duration_seconds: 365}
        ]
      },
      %{
        name: "Opaline Dreams",
        cover_image_url: "/images/albums/violet_depths_opaline_dreams.png",
        year_released: 2014,
        artist_name: "Violet Depths",
        tracks: [
          %{name: "Dawn's Soft Glow", duration: "5:10", duration_seconds: 310},
          %{name: "Pastel Skies", duration: "4:40", duration_seconds: 280},
          %{name: "Radiant Whisper", duration: "5:45", duration_seconds: 345},
          %{name: "Luminescence", duration: "3:50", duration_seconds: 230},
          %{name: "Color Shift", duration: "6:00", duration_seconds: 360},
          %{name: "Daydream Luster", duration: "4:25", duration_seconds: 265},
          %{name: "Prism of Light", duration: "5:15", duration_seconds: 315},
          %{name: "Opal Horizon", duration: "6:40", duration_seconds: 400},
          %{name: "Evening's Fade", duration: "5:01", duration_seconds: 301}
        ]
      },
      %{
        name: "Parallel Realities",
        cover_image_url: "/images/albums/infiniverse_parallel_realities.png",
        year_released: 2005,
        artist_name: "Infiniverse",
        tracks: [
          %{name: "Parallel Lives", duration: "5:16", duration_seconds: 316},
          %{name: "Dimensional Shift", duration: "4:45", duration_seconds: 285},
          %{name: "Alternate Echoes", duration: "5:55", duration_seconds: 355},
          %{name: "Realm of Shadows", duration: "6:10", duration_seconds: 370},
          %{name: "Visions Collide", duration: "7:00", duration_seconds: 420},
          %{name: "Beyond the Veil", duration: "5:30", duration_seconds: 330},
          %{name: "Interdimensional", duration: "4:55", duration_seconds: 295},
          %{name: "Quantum Entanglement", duration: "6:10", duration_seconds: 370},
          %{name: "Multiverse", duration: "4:35", duration_seconds: 275},
          %{name: "The Nexus", duration: "6:20", duration_seconds: 380}
        ]
      },
      %{
        name: "Recharge",
        cover_image_url: "/images/albums/static_shift_recharge.png",
        year_released: 2019,
        artist_name: "Static Shift",
        tracks: [
          %{name: "Surge", duration: "3:30", duration_seconds: 210},
          %{name: "Pulse", duration: "4:14", duration_seconds: 254},
          %{name: "Currents", duration: "5:06", duration_seconds: 306},
          %{name: "High Voltage", duration: "3:45", duration_seconds: 225},
          %{name: "Power Down", duration: "4:00", duration_seconds: 240},
          %{name: "Breaker", duration: "4:32", duration_seconds: 272},
          %{name: "Feedback Loop", duration: "3:58", duration_seconds: 238},
          %{name: "Gridlock", duration: "4:45", duration_seconds: 285},
          %{name: "Static Waves", duration: "5:10", duration_seconds: 310},
          %{name: "Circuit", duration: "3:27", duration_seconds: 207}
        ]
      },
      %{
        name: "Scarlet Dawn",
        cover_image_url: "/images/albums/tangerine_scarlet_dawn.png",
        year_released: 2020,
        artist_name: "Tangerine",
        tracks: [
          %{name: "Dawn Chorus", duration: "4:40", duration_seconds: 280},
          %{name: "Red Sky", duration: "5:12", duration_seconds: 312},
          %{name: "Morning Glow", duration: "4:20", duration_seconds: 260},
          %{name: "Awakening City", duration: "3:14", duration_seconds: 194},
          %{name: "First Light", duration: "4:18", duration_seconds: 258},
          %{name: "Sunlit Streets", duration: "5:35", duration_seconds: 335},
          %{name: "Daybreak", duration: "6:10", duration_seconds: 370},
          %{name: "Urban Sunrise", duration: "4:30", duration_seconds: 270},
          %{name: "Heat Haze", duration: "5:10", duration_seconds: 310},
          %{name: "Solar Flare", duration: "5:24", duration_seconds: 324}
        ]
      },
      %{
        name: "Serpent's Embrace",
        cover_image_url: "/images/albums/lithinex_serpents_embrace.png",
        year_released: 2021,
        artist_name: "Lithinex",
        tracks: [
          %{name: "Serpent's Whisper", duration: "4:35", duration_seconds: 275},
          %{name: "Embrace of the Abyss", duration: "7:40", duration_seconds: 460},
          %{name: "Venomous Grace", duration: "5:15", duration_seconds: 315},
          %{name: "Coil of Destiny", duration: "6:00", duration_seconds: 360},
          %{name: "Oracle of the Snake", duration: "5:50", duration_seconds: 350},
          %{name: "Shrouded in Scales", duration: "4:25", duration_seconds: 265},
          %{name: "Fangs of the Divine", duration: "4:47", duration_seconds: 287},
          %{name: "Slithering Fate", duration: "5:33", duration_seconds: 333},
          %{name: "Temple of the Serpent", duration: "6:22", duration_seconds: 382}
        ]
      },
      %{
        name: "Shadows of Infinity",
        cover_image_url: "/images/albums/hourglass_shadows_of_infinity.png",
        year_released: 2017,
        artist_name: "Hourglass",
        tracks: [
          %{name: "Ageless Voyage", duration: "5:10", duration_seconds: 310},
          %{name: "Stardust Cycle", duration: "4:55", duration_seconds: 295},
          %{name: "Infinite Echoes", duration: "5:40", duration_seconds: 340},
          %{name: "Celestial Decay", duration: "5:25", duration_seconds: 325},
          %{name: "Continuum", duration: "4:42", duration_seconds: 282},
          %{name: "Eventide Reverie", duration: "5:15", duration_seconds: 315},
          %{name: "Cosmos Requiem", duration: "6:00", duration_seconds: 360},
          %{name: "Gravity's Lament", duration: "4:44", duration_seconds: 284},
          %{name: "Temporal Veil", duration: "5:32", duration_seconds: 332},
          %{name: "Ouroboros", duration: "6:55", duration_seconds: 415}
        ]
      },
      %{
        name: "Shadows of Catnip",
        cover_image_url: "/images/albums/zombie_kittens_shadows_of_catnip.png",
        year_released: 2023,
        artist_name: "Zombie Kittens!!",
        tracks: [
          %{name: "Midnight Mew", duration: "4:05", duration_seconds: 245},
          %{name: "Black Cat Boogie", duration: "4:30", duration_seconds: 270},
          %{name: "Zombie Chase", duration: "3:50", duration_seconds: 230},
          %{name: "Catnip Shadows", duration: "5:00", duration_seconds: 300},
          %{name: "Purrfect Storm", duration: "4:15", duration_seconds: 255},
          %{name: "Hiss and Tell", duration: "3:55", duration_seconds: 235},
          %{name: "Dark Tails", duration: "4:40", duration_seconds: 280},
          %{name: "Night Hunter", duration: "5:25", duration_seconds: 325}
        ]
      },
      %{
        name: "Shanties of the Damned",
        cover_image_url: "/images/albums/crystal_cove_shanties_of_the_damned.png",
        year_released: 2023,
        artist_name: "Crystal Cove",
        tracks: [
          %{name: "Ghostly Winds", duration: "3:42", duration_seconds: 222},
          %{name: "Rum and Bones", duration: "4:15", duration_seconds: 255},
          %{name: "The Siren's Call", duration: "5:07", duration_seconds: 307},
          %{name: "Black Flag Risen", duration: "4:50", duration_seconds: 290},
          %{name: "Treasure Below", duration: "3:35", duration_seconds: 215},
          %{name: "Curse of the Cove", duration: "6:01", duration_seconds: 361},
          %{name: "Marooned", duration: "4:18", duration_seconds: 258},
          %{name: "The Kraken's Graph", duration: "5:32", duration_seconds: 332},
          %{name: "Jolly Roger", duration: "3:45", duration_seconds: 225},
          %{name: "Stormy Skies", duration: "4:10", duration_seconds: 250},
          %{name: "Depths Unknown", duration: "5:56", duration_seconds: 356}
        ]
      },
      %{
        name: "Silver Luminance",
        cover_image_url: "/images/albums/violet_depths_silver_luminance.png",
        year_released: 2012,
        artist_name: "Violet Depths",
        tracks: [
          %{name: "Moon's Reflection", duration: "4:55", duration_seconds: 295},
          %{name: "Silvery Veil", duration: "5:30", duration_seconds: 330},
          %{name: "Quiet Gleam", duration: "4:10", duration_seconds: 250},
          %{name: "Whispering Haze", duration: "6:15", duration_seconds: 375},
          %{name: "Echoes of Light", duration: "5:00", duration_seconds: 300},
          %{name: "Night's Silvered Sigh", duration: "4:35", duration_seconds: 275},
          %{name: "Glimmering Path", duration: "5:45", duration_seconds: 345},
          %{name: "Dreams in Chrome", duration: "4:50", duration_seconds: 290},
          %{name: "Mirror of the Sky", duration: "6:20", duration_seconds: 380}
        ]
      },
      %{
        name: "Spectral Dominion",
        cover_image_url: "/images/albums/vanadine_spectral_dominion.png",
        year_released: 2017,
        artist_name: "Vanadine",
        tracks: [
          %{name: "Ghosts of the Ancients", duration: "5:15", duration_seconds: 315},
          %{name: "Through the Abyss", duration: "4:53", duration_seconds: 293},
          %{name: "Dark Reverence", duration: "6:43", duration_seconds: 403},
          %{name: "Realm of the Spectres", duration: "5:00", duration_seconds: 300},
          %{name: "Under the Moon's Gaze", duration: "7:24", duration_seconds: 444},
          %{name: "The Hollow Men", duration: "4:45", duration_seconds: 285},
          %{name: "Silence in the Crypts", duration: "5:30", duration_seconds: 330},
          %{name: "Haunt of the Forsaken", duration: "6:09", duration_seconds: 369}
        ]
      },
      %{
        name: "Stahlstadt",
        cover_image_url: "/images/albums/resonanz_stahlstadt.png",
        year_released: 1996,
        artist_name: "Resonanz",
        tracks: [
          %{name: "Asche zu Asche", duration: "4:50", duration_seconds: 290},
          %{name: "Stahlherz", duration: "4:30", duration_seconds: 270},
          %{name: "Dunkle Flammen", duration: "5:15", duration_seconds: 315},
          %{name: "Nacht der Maschinen", duration: "5:00", duration_seconds: 300},
          %{name: "Eisenwelt", duration: "3:45", duration_seconds: 225},
          %{name: "Schattenläufer", duration: "4:55", duration_seconds: 295},
          %{name: "Industriegeist", duration: "4:20", duration_seconds: 260},
          %{name: "Rostige Ketten", duration: "6:10", duration_seconds: 370},
          %{name: "Halle der Echos", duration: "5:40", duration_seconds: 340},
          %{name: "Stahlstadt", duration: "7:30", duration_seconds: 450},
          %{name: "Maschinenherz", duration: "5:25", duration_seconds: 325}
        ]
      },
      %{
        name: "Světlo ve Tmě",
        year_released: 2019,
        artist_name: "Oáza",
        tracks: [
          %{name: "Ztracené sny", duration: "3:50", duration_seconds: 230},
          %{name: "Hlas noční", duration: "4:30", duration_seconds: 270},
          %{name: "Šeptání větru", duration: "4:15", duration_seconds: 255},
          %{name: "Stíny", duration: "5:00", duration_seconds: 300},
          %{name: "Ticho před bouří", duration: "3:45", duration_seconds: 225},
          %{name: "Zrcadlo duše", duration: "4:10", duration_seconds: 250},
          %{name: "Křehké světy", duration: "4:35", duration_seconds: 275},
          %{name: "Přízraky minulosti", duration: "3:44", duration_seconds: 224},
          %{name: "Oáza", duration: "5:25", duration_seconds: 325}
        ]
      },
      %{
        name: "Taivaslaulu",
        cover_image_url: "/images/albums/pilvipeite_taivaslaulu.png",
        year_released: 2015,
        artist_name: "Pilvipeite",
        tracks: [
          %{name: "Taivaanranta", duration: "4:50", duration_seconds: 290},
          %{name: "Kaukainen Kaiho", duration: "5:10", duration_seconds: 310},
          %{name: "Myrskylintu", duration: "4:35", duration_seconds: 275},
          %{name: "Hiljaiset Vedet", duration: "6:00", duration_seconds: 360},
          %{name: "Yön Syli", duration: "5:15", duration_seconds: 315},
          %{name: "Tuulenkantaja", duration: "4:43", duration_seconds: 283},
          %{name: "Revontulien Alla", duration: "7:00", duration_seconds: 420},
          %{name: "Syysillan Rauha", duration: "5:29", duration_seconds: 329},
          %{name: "Aamunkoi", duration: "4:01", duration_seconds: 241},
          %{name: "Taivaslaulu", duration: "9:40", duration_seconds: 580}
        ]
      },
      %{
        name: "Taranis Qarnix",
        cover_image_url: "/images/albums/anderon_taranis_qarnix.png",
        year_released: 2015,
        artist_name: "Anderon",
        tracks: [
          %{name: "Brigos", duration: "4:15", duration_seconds: 255},
          %{name: "Argantom", duration: "5:40", duration_seconds: 340},
          %{name: "Epom Uxello", duration: "4:30", duration_seconds: 270},
          %{name: "Carnonos", duration: "5:10", duration_seconds: 310},
          %{name: "Sironâ", duration: "4:50", duration_seconds: 290},
          %{name: "Auetos", duration: "5:15", duration_seconds: 315},
          %{name: "Segomâros", duration: "3:44", duration_seconds: 224},
          %{name: "Uernos", duration: "5:35", duration_seconds: 335},
          %{name: "Rodanos", duration: "6:10", duration_seconds: 370},
          %{name: "Ambiextos", duration: "4:35", duration_seconds: 275},
          %{name: "Andecambos", duration: "7:10", duration_seconds: 430}
        ]
      },
      %{
        name: "Threads of Aquamarine",
        cover_image_url: "/images/albums/tangerine_threads_of_aquamarine.png",
        year_released: 2022,
        artist_name: "Tangerine",
        tracks: [
          %{name: "Silken Pulse", duration: "5:10", duration_seconds: 310},
          %{name: "Woven Light", duration: "4:55", duration_seconds: 295},
          %{name: "Fiber of Time", duration: "5:42", duration_seconds: 342},
          %{name: "Echo Weave", duration: "3:57", duration_seconds: 237},
          %{name: "Chromatic Ties", duration: "5:15", duration_seconds: 315},
          %{name: "Loom of Dreams", duration: "4:50", duration_seconds: 290},
          %{name: "Knots of Fate", duration: "5:30", duration_seconds: 330},
          %{name: "Patchwork Souls", duration: "6:00", duration_seconds: 360},
          %{name: "Seamless", duration: "4:04", duration_seconds: 244},
          %{name: "Binding Melody", duration: "7:20", duration_seconds: 440}
        ]
      },
      %{
        name: "Throne of Isolation",
        cover_image_url: "/images/albums/vanadine_throne_of_isolation.png",
        year_released: 2014,
        artist_name: "Vanadine",
        tracks: [
          %{name: "Frostbite Monarch", duration: "4:50", duration_seconds: 290},
          %{name: "Whispering Shadows", duration: "3:29", duration_seconds: 209},
          %{name: "Solitude's Grasp", duration: "5:03", duration_seconds: 303},
          %{name: "Veil of Winter", duration: "4:40", duration_seconds: 280},
          %{name: "Crown of Ice", duration: "4:32", duration_seconds: 272},
          %{name: "The Frozen Wasteland", duration: "3:12", duration_seconds: 192},
          %{name: "Echoes of the Void", duration: "6:32", duration_seconds: 392},
          %{name: "Endless Night", duration: "6:00", duration_seconds: 360}
        ]
      },
      %{
        name: "Temporal Rift",
        cover_image_url: "/images/albums/infiniverse_temporal_rift.png",
        year_released: 2007,
        artist_name: "Infiniverse",
        tracks: [
          %{name: "Time Torn", duration: "4:35", duration_seconds: 275},
          %{name: "Rift", duration: "5:50", duration_seconds: 350},
          %{name: "Ageless Whisper", duration: "4:25", duration_seconds: 265},
          %{name: "Chrono Crossroads", duration: "6:40", duration_seconds: 400},
          %{name: "Epoch's End", duration: "7:30", duration_seconds: 450},
          %{name: "Cascade of Ages", duration: "5:25", duration_seconds: 325},
          %{name: "The Time Diver", duration: "4:44", duration_seconds: 284},
          %{name: "Warp", duration: "6:02", duration_seconds: 362},
          %{name: "Eternity's Gate", duration: "5:54", duration_seconds: 354},
          %{name: "Paradox", duration: "7:10", duration_seconds: 430}
        ]
      },
      %{
        name: "Under Starlit Skies",
        cover_image_url: "/images/albums/nights_in_the_nullarbor_under_starlit_skies.png",
        year_released: 2019,
        artist_name: "Nights in the Nullarbor",
        tracks: [
          %{name: "Nights in the Nullarbor", duration: "3:45", duration_seconds: 225},
          %{name: "Driftwood", duration: "4:20", duration_seconds: 260},
          %{name: "Wandering Star", duration: "5:10", duration_seconds: 310},
          %{name: "Echoes of the Road", duration: "3:50", duration_seconds: 230},
          %{name: "Campfire Constellations", duration: "4:33", duration_seconds: 273},
          %{name: "Solitude and Stardust", duration: "5:00", duration_seconds: 300},
          %{name: "Coastal Dreams", duration: "3:58", duration_seconds: 238},
          %{name: "Horizon Lines", duration: "4:15", duration_seconds: 255},
          %{name: "The Quiet Earth", duration: "4:50", duration_seconds: 290}
        ]
      },
      %{
        name: "Veil of the Oracle",
        cover_image_url: "/images/albums/lithinex_veil_of_the_oracle.png",
        year_released: 2018,
        artist_name: "Lithinex",
        tracks: [
          %{name: "Echoes of Prophecy", duration: "3:50", duration_seconds: 230},
          %{name: "Sight Beyond Sight", duration: "6:30", duration_seconds: 390},
          %{name: "Celestial Chains", duration: "4:15", duration_seconds: 255},
          %{name: "The Oracle's Gift", duration: "9:05", duration_seconds: 545},
          %{name: "Forbidden Wisdom", duration: "5:20", duration_seconds: 320},
          %{name: "Veiled Destinies", duration: "4:58", duration_seconds: 298},
          %{name: "Mystic Revelations", duration: "5:42", duration_seconds: 342},
          %{name: "The Seer's Journey", duration: "6:10", duration_seconds: 370},
          %{name: "Illumination", duration: "3:59", duration_seconds: 239}
        ]
      },
      %{
        name: "Verda Horizonto",
        cover_image_url: "/images/albums/cielarko_verda_horizonto.png",
        year_released: 2023,
        artist_name: "Ĉielarko",
        tracks: [
          %{name: "Vojaĝo al la Lumo", duration: "4:20", duration_seconds: 260},
          %{name: "Arbaraj Sentoj", duration: "3:55", duration_seconds: 235},
          %{name: "Flustro de la Vento", duration: "5:10", duration_seconds: 310},
          %{name: "La Danco de la Folioj", duration: "4:45", duration_seconds: 285},
          %{name: "Sub la Ĉielarko", duration: "6:02", duration_seconds: 362},
          %{name: "Herbeja Vekiĝo", duration: "3:40", duration_seconds: 220},
          %{name: "Fajro de la Animo", duration: "5:14", duration_seconds: 314},
          %{name: "Nokta Sereno", duration: "4:31", duration_seconds: 271}
        ]
      },
      %{
        name: "Violet Dream",
        cover_image_url: "/images/albums/tangerine_violet_dream.png",
        year_released: 2015,
        artist_name: "Tangerine",
        tracks: [
          %{name: "Neon Nightfall", duration: "5:05", duration_seconds: 305},
          %{name: "Lavender Shadows", duration: "4:43", duration_seconds: 283},
          %{name: "Purple Haze", duration: "4:02", duration_seconds: 242},
          %{name: "Twilight Fantasy", duration: "6:01", duration_seconds: 361},
          %{name: "Mystic Spectrum", duration: "4:36", duration_seconds: 276},
          %{name: "Violet Pulse", duration: "3:44", duration_seconds: 224},
          %{name: "Ultraviolet", duration: "3:36", duration_seconds: 216},
          %{name: "Dream in Indigo", duration: "4:45", duration_seconds: 285},
          %{name: "Nightshade Serenade", duration: "5:12", duration_seconds: 312},
          %{name: "Lilac Light", duration: "6:30", duration_seconds: 390}
        ]
      },
      %{
        name: "Viridian Echo",
        cover_image_url: "/images/albums/tangerine_viridian_echo.png",
        year_released: 2016,
        artist_name: "Tangerine",
        tracks: [
          %{name: "Forest Synapse", duration: "5:02", duration_seconds: 302},
          %{name: "Verdant Dreams", duration: "4:42", duration_seconds: 282},
          %{name: "Glow of the Glade", duration: "3:35", duration_seconds: 215},
          %{name: "Whispering Leaves", duration: "5:13", duration_seconds: 313},
          %{name: "Green Mist", duration: "4:39", duration_seconds: 279},
          %{name: "Photosynthesis Pulse", duration: "5:01", duration_seconds: 301},
          %{name: "Emerald Light", duration: "4:22", duration_seconds: 262},
          %{name: "Vines of Time", duration: "6:33", duration_seconds: 393},
          %{name: "Canopy Dance", duration: "5:02", duration_seconds: 302},
          %{name: "Mossy Veil", duration: "4:55", duration_seconds: 295}
        ]
      },
      %{
        name: "Voiles de l'ombre",
        cover_image_url: "/images/albums/lorchestre_obscur_voiles_de_lombre.png",
        year_released: 2018,
        artist_name: "L'orchestre obscur",
        tracks: [
          %{name: "Murmures de la forêt", duration: "6:10", duration_seconds: 370},
          %{name: "Crépuscule des âmes", duration: "5:45", duration_seconds: 345},
          %{name: "L'écho des vides", duration: "7:30", duration_seconds: 450},
          %{name: "Résonance nocturne", duration: "6:00", duration_seconds: 360},
          %{name: "Sombres rêveries", duration: "5:20", duration_seconds: 320},
          %{name: "Entre les ombres", duration: "8:15", duration_seconds: 495},
          %{name: "Visions éphémères", duration: "4:40", duration_seconds: 280},
          %{name: "Voile de mystère", duration: "7:50", duration_seconds: 470}
        ]
      },
      %{
        name: "Whisker Wonderland",
        cover_image_url: "/images/albums/zombie_kittens_whisker_wonderland.png",
        year_released: 2021,
        artist_name: "Zombie Kittens!!",
        tracks: [
          %{name: "Kittens Assemble", duration: "3:55", duration_seconds: 235},
          %{name: "Snowpaw Serenade", duration: "4:40", duration_seconds: 280},
          %{name: "Feline Fantasia", duration: "4:25", duration_seconds: 265},
          %{name: "Ghostly Whispers", duration: "4:50", duration_seconds: 290},
          %{name: "Mewment of Glory", duration: "3:35", duration_seconds: 215},
          %{name: "Litterbox Lullaby", duration: "5:15", duration_seconds: 315},
          %{name: "Yarnball Chronicles", duration: "4:45", duration_seconds: 285},
          %{name: "White Whisker Waltz", duration: "4:30", duration_seconds: 270}
        ]
      },
      %{
        name: "Wild",
        cover_image_url: "/images/albums/nights_in_the_nullarbor_wild.png",
        year_released: 2023,
        artist_name: "Nights in the Nullarbor",
        tracks: [
          %{name: "Whispering Woods", duration: "3:50", duration_seconds: 230},
          %{name: "Twilight Trails", duration: "4:10", duration_seconds: 250},
          %{name: "Moonlit Canopy", duration: "5:15", duration_seconds: 315},
          %{name: "Secrets of the Soil", duration: "4:00", duration_seconds: 240},
          %{name: "Nightfall Chorus", duration: "5:30", duration_seconds: 330},
          %{name: "Unseen Paths", duration: "3:45", duration_seconds: 225},
          %{name: "Beneath the Stars", duration: "4:55", duration_seconds: 295},
          %{name: "Wild Heart", duration: "4:20", duration_seconds: 260},
          %{name: "Nature's Embrace ", duration: "4:35", duration_seconds: 275},
          %{name: "Dawn's First Light", duration: "5:05", duration_seconds: 305}
        ]
      },
      %{
        name: "Тень Проклятия",
        cover_image_url: "/images/albums/Черная_Луна_Тень_Проклятия.png",
        year_released: 2019,
        artist_name: "Черная Луна",
        tracks: [
          %{name: "Ворон", duration: "4:15", duration_seconds: 255},
          %{name: "Последний дух", duration: "5:00", duration_seconds: 300},
          %{name: "Кровавый след", duration: "3:45", duration_seconds: 225},
          %{name: "Темные воды", duration: "4:50", duration_seconds: 290},
          %{name: "Проклятие земли", duration: "6:10", duration_seconds: 370},
          %{name: "Шепот предков", duration: "5:35", duration_seconds: 335},
          %{name: "Забытый храм", duration: "4:20", duration_seconds: 260},
          %{name: "Зов предков", duration: "4:55", duration_seconds: 295},
          %{name: "Замерзшая душа", duration: "5:30", duration_seconds: 330},
          %{name: "Лесной мрак", duration: "4:40", duration_seconds: 280},
          %{name: "Око тьмы", duration: "6:15", duration_seconds: 375}
        ]
      },
      %{
        name: "Вечная ночь",
        cover_image_url: "/images/albums/Черная_Луна_Вечная_ночь.png",
        year_released: 2019,
        artist_name: "Черная Луна",
        tracks: [
          %{name: "Ночной страж", duration: "4:55", duration_seconds: 295},
          %{name: "Ледяное дыхание", duration: "5:40", duration_seconds: 340},
          %{name: "Призраки прошлого", duration: "4:35", duration_seconds: 275},
          %{name: "Крик бездны", duration: "6:25", duration_seconds: 385},
          %{name: "Судьба во тьме", duration: "5:50", duration_seconds: 350},
          %{name: "Черное солнце", duration: "4:30", duration_seconds: 270},
          %{name: "Вечная ночь", duration: "7:15", duration_seconds: 435},
          %{name: "Затмение", duration: "4:50", duration_seconds: 290},
          %{name: "Пепел прошлого", duration: "5:25", duration_seconds: 325},
          %{name: "Тихий ужас", duration: "6:00", duration_seconds: 360},
          %{name: "Стражи мрака", duration: "5:40", duration_seconds: 340},
          %{name: "Сквозь ночь", duration: "7:00", duration_seconds: 420}
        ]
      }
    ]
  end
end
