const fs = require("fs");
const path = require("path");

const PLUGIN_NAME = "ElmTypesRspackPlugin";

/**
 * Generates a `<file>.elm.d.ts` next to every compiled `.elm` module, using
 * lydell/elm-ts-types to type the module's `init`, flags, and ports.
 *
 * Reuses the already-compiled JS from elm-webpack-loader (via
 * `module.originalSource()`) instead of invoking `elm make` a second time,
 * since elm-ts-types needs the exact, unwrapped compiler output to `eval`.
 *
 * Skips the actual file write when the generated output is byte-identical
 * to what's already on disk, so an unrelated recompile (e.g. a view-only
 * change) doesn't bump the `.d.ts` mtime and trigger downstream watchers
 * (editor TS servers, `tsc --watch`, etc.) for no reason.
 *
 * Logs through the standard rspack/webpack Logger, so debug output is off
 * by default. Enable it with either:
 *   stats: { loggingDebug: ["ElmTypesRspackPlugin"] }
 *   stats: { logging: "verbose" }
 *
 * @example
 * new ElmTypesRspackPlugin()
 * new ElmTypesRspackPlugin({ test: /\.elm$/ })
 */
class ElmTypesRspackPlugin {
  /**
   * @param {object} [options]
   * @param {RegExp} [options.test] Matches module resource paths to generate
   *   types for. Defaults to any `.elm` file.
   */
  constructor({ test = /\.elm$/ } = {}) {
    this.test = test;
    this.generateTypeScriptPromise = import("elm-ts-types").then(
      ({ generateTypeScript }) => generateTypeScript,
    );
  }

  /**
   * Writes `<resource>.d.ts` from the given compiled Elm JS, skipping the
   * write if the generated content matches what's already on disk.
   *
   * @param {string} resource Absolute path to the `.elm` source file.
   * @param {string} compiledJs Raw `elm make` output for that file.
   * @param {import("webpack").Logger} logger
   * @param {string} context Project root, used only to shorten log output.
   * @returns {Promise<void>}
   */
  generate(resource, compiledJs, logger, context) {
    return this.generateTypeScriptPromise.then((generateTypeScript) => {
      const typeDefinition = `// Generated by ${PLUGIN_NAME}. Manual edits will be lost.
${generateTypeScript(compiledJs)}
export const Elm: typeof Elm;
`;
      const outputPath = `${resource}.d.ts`;
      const relativeOutputPath = path.relative(context, outputPath);

      let previous;
      try {
        previous = fs.readFileSync(outputPath, "utf8");
      } catch {
        previous = null;
      }

      if (previous === typeDefinition) {
        logger.debug(`unchanged, skipped writing "${relativeOutputPath}"`);
        return;
      }

      fs.writeFileSync(outputPath, typeDefinition);
      logger.debug(`generated types for "${relativeOutputPath}"`);
    });
  }

  apply(compiler) {
    compiler.hooks.compilation.tap(PLUGIN_NAME, (compilation) => {
      const logger = compilation.getLogger(PLUGIN_NAME);

      // succeedModule is synchronous, so generation runs fire-and-forget per
      // module. Each attempt is tracked here and awaited in finishModules,
      // which delays sealing the compilation until generation has settled,
      // so any failure still lands in this build's compilation.errors.
      const pending = [];

      compilation.hooks.succeedModule.tap(PLUGIN_NAME, (module) => {
        const resource = module.resource;
        if (!resource || !this.test.test(resource)) {
          return;
        }

        const relativeResource = path.relative(compiler.context, resource);

        const source = module.originalSource && module.originalSource();
        if (!source) {
          logger.debug(`skipping "${relativeResource}": no source available`);
          return;
        }

        pending.push(
          this.generate(
            resource,
            source.source().toString(),
            logger,
            compiler.context,
          ).catch((error) => {
            compilation.errors.push(
              new Error(
                `${PLUGIN_NAME} failed for "${relativeResource}": ${error.message}`,
              ),
            );
          }),
        );
      });

      compilation.hooks.finishModules.tapPromise(PLUGIN_NAME, () => Promise.all(pending));
    });
  }
}

module.exports = ElmTypesRspackPlugin;
