const fs = require("fs");
const os = require("os");
const path = require("path");
const { execFileSync } = require("child_process");

const PLUGIN_NAME = "ElmTypesRspackPlugin";

class ElmTypesRspackPlugin {
  constructor({ elmBinary, test = /\.elm$/ }) {
    this.elmBinary = elmBinary;
    this.test = test;
    this.generateTypeScriptPromise = import("elm-ts-types").then(
      ({ generateTypeScript }) => generateTypeScript,
    );
  }

  generate(resource, cwd) {
    const tempJsPath = path.join(
      os.tmpdir(),
      `elm-ts-types-${Date.now()}-${Math.random().toString(36).slice(2)}.js`,
    );

    let compiledJs;
    try {
      execFileSync(
        this.elmBinary,
        ["make", resource, "--output", tempJsPath],
        { cwd },
      );
      compiledJs = fs.readFileSync(tempJsPath, "utf8");
      fs.rmSync(tempJsPath);
    } catch (error) {
      return Promise.reject(error);
    }

    return this.generateTypeScriptPromise.then((generateTypeScript) => {
      const typeDefinition = `// Generated by ${PLUGIN_NAME}. Manual edits will be lost.
${generateTypeScript(compiledJs)}
export const Elm: typeof Elm;
`;
      fs.writeFileSync(`${resource}.d.ts`, typeDefinition);
    });
  }

  apply(compiler) {
    compiler.hooks.compilation.tap(PLUGIN_NAME, (compilation) => {
      compilation.hooks.succeedModule.tap(PLUGIN_NAME, (module) => {
        const resource = module.resource;
        if (!resource || !this.test.test(resource)) {
          return;
        }

        this.generate(resource, compiler.context).catch((error) => {
          console.error(`${PLUGIN_NAME} failed for ${resource}:`, error);
        });
      });
    });
  }
}

module.exports = ElmTypesRspackPlugin;
