const fs = require("fs");

const PLUGIN_NAME = "ElmTypesRspackPlugin";

class ElmTypesRspackPlugin {
  constructor({ test = /\.elm$/ } = {}) {
    this.test = test;
    this.generateTypeScriptPromise = import("elm-ts-types").then(
      ({ generateTypeScript }) => generateTypeScript,
    );
  }

  generate(resource, compiledJs) {
    return this.generateTypeScriptPromise.then((generateTypeScript) => {
      const typeDefinition = `// Generated by ${PLUGIN_NAME}. Manual edits will be lost.
${generateTypeScript(compiledJs)}
export const Elm: typeof Elm;
`;
      fs.writeFileSync(`${resource}.d.ts`, typeDefinition);
    });
  }

  apply(compiler) {
    compiler.hooks.compilation.tap(PLUGIN_NAME, (compilation) => {
      // succeedModule is synchronous, so generation runs fire-and-forget per
      // module. Each attempt is tracked here and awaited in finishModules,
      // which delays sealing the compilation until generation has settled,
      // so any failure still lands in this build's compilation.errors.
      const pending = [];

      compilation.hooks.succeedModule.tap(PLUGIN_NAME, (module) => {
        const resource = module.resource;
        if (!resource || !this.test.test(resource)) {
          return;
        }

        const source = module.originalSource && module.originalSource();
        if (!source) {
          return;
        }

        pending.push(
          this.generate(resource, source.source().toString()).catch(
            (error) => {
              compilation.errors.push(
                new Error(`${PLUGIN_NAME} failed for ${resource}: ${error.message}`),
              );
            },
          ),
        );
      });

      compilation.hooks.finishModules.tapPromise(PLUGIN_NAME, () =>
        Promise.all(pending),
      );
    });
  }
}

module.exports = ElmTypesRspackPlugin;
